services:
  reportes_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: reportes_app
    container_name: reportes_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8003:8000"
    depends_on:
      - reportes_db

  reportes_db:
    image: mysql:8.0
    container_name: reportes_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reportes_db
    ports:
      - "3309:3306"
    volumes:
      - reportes_mysql:/var/lib/mysql

volumes:
  reportes_mysql:
