version: '3.8'

services:
  reportes_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: reportes_app
    container_name: reportes_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - reportes_storage:/var/www/storage
    ports:
      - "8002:8002"
    networks:
      - micro_red
    environment:
      APP_ENV: local
      APP_KEY: base64:xPxxxxxx
      DB_CONNECTION: mysql
      DB_HOST: reservas_db
      DB_PORT: 3306
      DB_DATABASE: reservas_db
      DB_USERNAME: reservas
      DB_PASSWORD: reservas


networks:
  micro_red:
    external: true

volumes:
  reportes_storage:
