version: '3.8'

services:
  gestion_clases:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=microservicio_gestion_clases
    depends_on:
      - mongo
    networks:
      - micro_red

  mongo:
    image: mongo:6.0
    container_name: mongo_gestion_clases
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - micro_red

networks:
  micro_red:
    external: true

volumes:
  mongo_data:
    driver: local
    