version: '3.8'

services:
  recomendaciones_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recomendaciones_app
    restart: unless-stopped
    ports:
      - "5003:5003"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: microservicio_gestion_recomendaciones
    depends_on:
      - mongo
    networks:
      - micro_red
    
  mongo:
    image: mongo:6.0
    container_name: mongo_gestion_recomendaciones
    restart: unless-stopped
    ports:
      - "2717:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - micro_red

networks:
  micro_red:
    external: true

volumes:
  mongo_data:
    driver: local
