services:
  reservas_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservas_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: >
      sh -c "
      sleep 10 &&
      php artisan serve --host=0.0.0.0 --port=8000
      "
    ports:
      - "8003:8000"
    depends_on:
      - reservas_db
    networks:
      - micro_red

  reservas_db:
    image: mysql:8.0
    container_name: reservas_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservas_db
      MYSQL_USER: reservas
      MYSQL_PASSWORD: reservas
    ports:
      - "3307:3306"
    volumes:
      - reservas_data:/var/lib/mysql
    networks:
      - micro_red

networks:
  micro_red:
    external: true

volumes:
  reservas_data:
